# -*- coding: utf-8 -*-
"""IRIS FLOWER CLASSIFICATION.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cek4KEP-DIQYKKRzjOKuTfm2DzG7fa22

# IRIS FLOWER CLASSIFICATION
"""

import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd

"""# Load the Iris dataset from a CSV file into a pandas DataFrame named df."""

df = pd.read_csv("/content/Iris.csv")

df

"""# Generates descriptive statistics of the DataFrame df"""

df.describe()

data = df.values
x = data[:,1:4]
y = data[:,5]
y

from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2)
y_train

# Algorithm - Support vector machine
from sklearn.svm import SVC
svn = SVC()
svn.fit(x_train, y_train)

predictions = svn.predict(x_test)
from sklearn.metrics import accuracy_score
acc = accuracy_score(y_test, predictions)*100
print('%.2f' %acc)

from sklearn.metrics import classification_report
print(classification_report(y_test, predictions))